// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	big "math/big"

	abi "github.com/ethereum/go-ethereum/accounts/abi"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	core "github.com/ethereum/go-ethereum/core"

	mock "github.com/stretchr/testify/mock"

	statedb "github.com/cosmos/evm/x/vm/statedb"

	tracing "github.com/ethereum/go-ethereum/core/tracing"

	types "github.com/cosmos/cosmos-sdk/types"

	vmtypes "github.com/cosmos/evm/x/vm/types"
)

// EVMKeeper is an autogenerated mock type for the EVMKeeper type
type EVMKeeper struct {
	mock.Mock
}

type EVMKeeper_Expecter struct {
	mock *mock.Mock
}

func (_m *EVMKeeper) EXPECT() *EVMKeeper_Expecter {
	return &EVMKeeper_Expecter{mock: &_m.Mock}
}

// ApplyMessage provides a mock function with given fields: ctx, msg, tracer, commit, internal
func (_m *EVMKeeper) ApplyMessage(ctx types.Context, msg core.Message, tracer *tracing.Hooks, commit bool, internal bool) (*vmtypes.MsgEthereumTxResponse, error) {
	ret := _m.Called(ctx, msg, tracer, commit, internal)

	if len(ret) == 0 {
		panic("no return value specified for ApplyMessage")
	}

	var r0 *vmtypes.MsgEthereumTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Context, core.Message, *tracing.Hooks, bool, bool) (*vmtypes.MsgEthereumTxResponse, error)); ok {
		return rf(ctx, msg, tracer, commit, internal)
	}
	if rf, ok := ret.Get(0).(func(types.Context, core.Message, *tracing.Hooks, bool, bool) *vmtypes.MsgEthereumTxResponse); ok {
		r0 = rf(ctx, msg, tracer, commit, internal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmtypes.MsgEthereumTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Context, core.Message, *tracing.Hooks, bool, bool) error); ok {
		r1 = rf(ctx, msg, tracer, commit, internal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EVMKeeper_ApplyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMessage'
type EVMKeeper_ApplyMessage_Call struct {
	*mock.Call
}

// ApplyMessage is a helper method to define mock.On call
//   - ctx types.Context
//   - msg core.Message
//   - tracer *tracing.Hooks
//   - commit bool
//   - internal bool
func (_e *EVMKeeper_Expecter) ApplyMessage(ctx interface{}, msg interface{}, tracer interface{}, commit interface{}, internal interface{}) *EVMKeeper_ApplyMessage_Call {
	return &EVMKeeper_ApplyMessage_Call{Call: _e.mock.On("ApplyMessage", ctx, msg, tracer, commit, internal)}
}

func (_c *EVMKeeper_ApplyMessage_Call) Run(run func(ctx types.Context, msg core.Message, tracer *tracing.Hooks, commit bool, internal bool)) *EVMKeeper_ApplyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(core.Message), args[2].(*tracing.Hooks), args[3].(bool), args[4].(bool))
	})
	return _c
}

func (_c *EVMKeeper_ApplyMessage_Call) Return(_a0 *vmtypes.MsgEthereumTxResponse, _a1 error) *EVMKeeper_ApplyMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EVMKeeper_ApplyMessage_Call) RunAndReturn(run func(types.Context, core.Message, *tracing.Hooks, bool, bool) (*vmtypes.MsgEthereumTxResponse, error)) *EVMKeeper_ApplyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CallEVM provides a mock function with given fields: ctx, _a1, from, contract, commit, gasCap, method, args
func (_m *EVMKeeper) CallEVM(ctx types.Context, _a1 abi.ABI, from common.Address, contract common.Address, commit bool, gasCap *big.Int, method string, args ...interface{}) (*vmtypes.MsgEthereumTxResponse, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, _a1, from, contract, commit, gasCap, method)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CallEVM")
	}

	var r0 *vmtypes.MsgEthereumTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Context, abi.ABI, common.Address, common.Address, bool, *big.Int, string, ...interface{}) (*vmtypes.MsgEthereumTxResponse, error)); ok {
		return rf(ctx, _a1, from, contract, commit, gasCap, method, args...)
	}
	if rf, ok := ret.Get(0).(func(types.Context, abi.ABI, common.Address, common.Address, bool, *big.Int, string, ...interface{}) *vmtypes.MsgEthereumTxResponse); ok {
		r0 = rf(ctx, _a1, from, contract, commit, gasCap, method, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmtypes.MsgEthereumTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Context, abi.ABI, common.Address, common.Address, bool, *big.Int, string, ...interface{}) error); ok {
		r1 = rf(ctx, _a1, from, contract, commit, gasCap, method, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EVMKeeper_CallEVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEVM'
type EVMKeeper_CallEVM_Call struct {
	*mock.Call
}

// CallEVM is a helper method to define mock.On call
//   - ctx types.Context
//   - _a1 abi.ABI
//   - from common.Address
//   - contract common.Address
//   - commit bool
//   - gasCap *big.Int
//   - method string
//   - args ...interface{}
func (_e *EVMKeeper_Expecter) CallEVM(ctx interface{}, _a1 interface{}, from interface{}, contract interface{}, commit interface{}, gasCap interface{}, method interface{}, args ...interface{}) *EVMKeeper_CallEVM_Call {
	return &EVMKeeper_CallEVM_Call{Call: _e.mock.On("CallEVM",
		append([]interface{}{ctx, _a1, from, contract, commit, gasCap, method}, args...)...)}
}

func (_c *EVMKeeper_CallEVM_Call) Run(run func(ctx types.Context, _a1 abi.ABI, from common.Address, contract common.Address, commit bool, gasCap *big.Int, method string, args ...interface{})) *EVMKeeper_CallEVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-7)
		for i, a := range args[7:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(types.Context), args[1].(abi.ABI), args[2].(common.Address), args[3].(common.Address), args[4].(bool), args[5].(*big.Int), args[6].(string), variadicArgs...)
	})
	return _c
}

func (_c *EVMKeeper_CallEVM_Call) Return(_a0 *vmtypes.MsgEthereumTxResponse, _a1 error) *EVMKeeper_CallEVM_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EVMKeeper_CallEVM_Call) RunAndReturn(run func(types.Context, abi.ABI, common.Address, common.Address, bool, *big.Int, string, ...interface{}) (*vmtypes.MsgEthereumTxResponse, error)) *EVMKeeper_CallEVM_Call {
	_c.Call.Return(run)
	return _c
}

// CallEVMWithData provides a mock function with given fields: ctx, from, contract, data, commit, gasCap
func (_m *EVMKeeper) CallEVMWithData(ctx types.Context, from common.Address, contract *common.Address, data []byte, commit bool, gasCap *big.Int) (*vmtypes.MsgEthereumTxResponse, error) {
	ret := _m.Called(ctx, from, contract, data, commit, gasCap)

	if len(ret) == 0 {
		panic("no return value specified for CallEVMWithData")
	}

	var r0 *vmtypes.MsgEthereumTxResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Context, common.Address, *common.Address, []byte, bool, *big.Int) (*vmtypes.MsgEthereumTxResponse, error)); ok {
		return rf(ctx, from, contract, data, commit, gasCap)
	}
	if rf, ok := ret.Get(0).(func(types.Context, common.Address, *common.Address, []byte, bool, *big.Int) *vmtypes.MsgEthereumTxResponse); ok {
		r0 = rf(ctx, from, contract, data, commit, gasCap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmtypes.MsgEthereumTxResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Context, common.Address, *common.Address, []byte, bool, *big.Int) error); ok {
		r1 = rf(ctx, from, contract, data, commit, gasCap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EVMKeeper_CallEVMWithData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallEVMWithData'
type EVMKeeper_CallEVMWithData_Call struct {
	*mock.Call
}

// CallEVMWithData is a helper method to define mock.On call
//   - ctx types.Context
//   - from common.Address
//   - contract *common.Address
//   - data []byte
//   - commit bool
//   - gasCap *big.Int
func (_e *EVMKeeper_Expecter) CallEVMWithData(ctx interface{}, from interface{}, contract interface{}, data interface{}, commit interface{}, gasCap interface{}) *EVMKeeper_CallEVMWithData_Call {
	return &EVMKeeper_CallEVMWithData_Call{Call: _e.mock.On("CallEVMWithData", ctx, from, contract, data, commit, gasCap)}
}

func (_c *EVMKeeper_CallEVMWithData_Call) Run(run func(ctx types.Context, from common.Address, contract *common.Address, data []byte, commit bool, gasCap *big.Int)) *EVMKeeper_CallEVMWithData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address), args[2].(*common.Address), args[3].([]byte), args[4].(bool), args[5].(*big.Int))
	})
	return _c
}

func (_c *EVMKeeper_CallEVMWithData_Call) Return(_a0 *vmtypes.MsgEthereumTxResponse, _a1 error) *EVMKeeper_CallEVMWithData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EVMKeeper_CallEVMWithData_Call) RunAndReturn(run func(types.Context, common.Address, *common.Address, []byte, bool, *big.Int) (*vmtypes.MsgEthereumTxResponse, error)) *EVMKeeper_CallEVMWithData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, addr
func (_m *EVMKeeper) DeleteAccount(ctx types.Context, addr common.Address) error {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Context, common.Address) error); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EVMKeeper_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type EVMKeeper_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - addr common.Address
func (_e *EVMKeeper_Expecter) DeleteAccount(ctx interface{}, addr interface{}) *EVMKeeper_DeleteAccount_Call {
	return &EVMKeeper_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, addr)}
}

func (_c *EVMKeeper_DeleteAccount_Call) Run(run func(ctx types.Context, addr common.Address)) *EVMKeeper_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *EVMKeeper_DeleteAccount_Call) Return(_a0 error) *EVMKeeper_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_DeleteAccount_Call) RunAndReturn(run func(types.Context, common.Address) error) *EVMKeeper_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// EstimateGasInternal provides a mock function with given fields: c, req, fromType
func (_m *EVMKeeper) EstimateGasInternal(c context.Context, req *vmtypes.EthCallRequest, fromType vmtypes.CallType) (*vmtypes.EstimateGasResponse, error) {
	ret := _m.Called(c, req, fromType)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGasInternal")
	}

	var r0 *vmtypes.EstimateGasResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *vmtypes.EthCallRequest, vmtypes.CallType) (*vmtypes.EstimateGasResponse, error)); ok {
		return rf(c, req, fromType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *vmtypes.EthCallRequest, vmtypes.CallType) *vmtypes.EstimateGasResponse); ok {
		r0 = rf(c, req, fromType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vmtypes.EstimateGasResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *vmtypes.EthCallRequest, vmtypes.CallType) error); ok {
		r1 = rf(c, req, fromType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EVMKeeper_EstimateGasInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGasInternal'
type EVMKeeper_EstimateGasInternal_Call struct {
	*mock.Call
}

// EstimateGasInternal is a helper method to define mock.On call
//   - c context.Context
//   - req *vmtypes.EthCallRequest
//   - fromType vmtypes.CallType
func (_e *EVMKeeper_Expecter) EstimateGasInternal(c interface{}, req interface{}, fromType interface{}) *EVMKeeper_EstimateGasInternal_Call {
	return &EVMKeeper_EstimateGasInternal_Call{Call: _e.mock.On("EstimateGasInternal", c, req, fromType)}
}

func (_c *EVMKeeper_EstimateGasInternal_Call) Run(run func(c context.Context, req *vmtypes.EthCallRequest, fromType vmtypes.CallType)) *EVMKeeper_EstimateGasInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vmtypes.EthCallRequest), args[2].(vmtypes.CallType))
	})
	return _c
}

func (_c *EVMKeeper_EstimateGasInternal_Call) Return(_a0 *vmtypes.EstimateGasResponse, _a1 error) *EVMKeeper_EstimateGasInternal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EVMKeeper_EstimateGasInternal_Call) RunAndReturn(run func(context.Context, *vmtypes.EthCallRequest, vmtypes.CallType) (*vmtypes.EstimateGasResponse, error)) *EVMKeeper_EstimateGasInternal_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, address
func (_m *EVMKeeper) GetAccount(ctx types.Context, address common.Address) *statedb.Account {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *statedb.Account
	if rf, ok := ret.Get(0).(func(types.Context, common.Address) *statedb.Account); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statedb.Account)
		}
	}

	return r0
}

// EVMKeeper_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type EVMKeeper_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - address common.Address
func (_e *EVMKeeper_Expecter) GetAccount(ctx interface{}, address interface{}) *EVMKeeper_GetAccount_Call {
	return &EVMKeeper_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, address)}
}

func (_c *EVMKeeper_GetAccount_Call) Run(run func(ctx types.Context, address common.Address)) *EVMKeeper_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *EVMKeeper_GetAccount_Call) Return(_a0 *statedb.Account) *EVMKeeper_GetAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_GetAccount_Call) RunAndReturn(run func(types.Context, common.Address) *statedb.Account) *EVMKeeper_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountWithoutBalance provides a mock function with given fields: ctx, addr
func (_m *EVMKeeper) GetAccountWithoutBalance(ctx types.Context, addr common.Address) *statedb.Account {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountWithoutBalance")
	}

	var r0 *statedb.Account
	if rf, ok := ret.Get(0).(func(types.Context, common.Address) *statedb.Account); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*statedb.Account)
		}
	}

	return r0
}

// EVMKeeper_GetAccountWithoutBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountWithoutBalance'
type EVMKeeper_GetAccountWithoutBalance_Call struct {
	*mock.Call
}

// GetAccountWithoutBalance is a helper method to define mock.On call
//   - ctx types.Context
//   - addr common.Address
func (_e *EVMKeeper_Expecter) GetAccountWithoutBalance(ctx interface{}, addr interface{}) *EVMKeeper_GetAccountWithoutBalance_Call {
	return &EVMKeeper_GetAccountWithoutBalance_Call{Call: _e.mock.On("GetAccountWithoutBalance", ctx, addr)}
}

func (_c *EVMKeeper_GetAccountWithoutBalance_Call) Run(run func(ctx types.Context, addr common.Address)) *EVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *EVMKeeper_GetAccountWithoutBalance_Call) Return(_a0 *statedb.Account) *EVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_GetAccountWithoutBalance_Call) RunAndReturn(run func(types.Context, common.Address) *statedb.Account) *EVMKeeper_GetAccountWithoutBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetCode provides a mock function with given fields: ctx, hash
func (_m *EVMKeeper) GetCode(ctx types.Context, hash common.Hash) []byte {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func(types.Context, common.Hash) []byte); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// EVMKeeper_GetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCode'
type EVMKeeper_GetCode_Call struct {
	*mock.Call
}

// GetCode is a helper method to define mock.On call
//   - ctx types.Context
//   - hash common.Hash
func (_e *EVMKeeper_Expecter) GetCode(ctx interface{}, hash interface{}) *EVMKeeper_GetCode_Call {
	return &EVMKeeper_GetCode_Call{Call: _e.mock.On("GetCode", ctx, hash)}
}

func (_c *EVMKeeper_GetCode_Call) Run(run func(ctx types.Context, hash common.Hash)) *EVMKeeper_GetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *EVMKeeper_GetCode_Call) Return(_a0 []byte) *EVMKeeper_GetCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_GetCode_Call) RunAndReturn(run func(types.Context, common.Hash) []byte) *EVMKeeper_GetCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetParams provides a mock function with given fields: ctx
func (_m *EVMKeeper) GetParams(ctx types.Context) vmtypes.Params {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetParams")
	}

	var r0 vmtypes.Params
	if rf, ok := ret.Get(0).(func(types.Context) vmtypes.Params); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(vmtypes.Params)
	}

	return r0
}

// EVMKeeper_GetParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParams'
type EVMKeeper_GetParams_Call struct {
	*mock.Call
}

// GetParams is a helper method to define mock.On call
//   - ctx types.Context
func (_e *EVMKeeper_Expecter) GetParams(ctx interface{}) *EVMKeeper_GetParams_Call {
	return &EVMKeeper_GetParams_Call{Call: _e.mock.On("GetParams", ctx)}
}

func (_c *EVMKeeper_GetParams_Call) Run(run func(ctx types.Context)) *EVMKeeper_GetParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context))
	})
	return _c
}

func (_c *EVMKeeper_GetParams_Call) Return(_a0 vmtypes.Params) *EVMKeeper_GetParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_GetParams_Call) RunAndReturn(run func(types.Context) vmtypes.Params) *EVMKeeper_GetParams_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailableStaticPrecompile provides a mock function with given fields: params, address
func (_m *EVMKeeper) IsAvailableStaticPrecompile(params *vmtypes.Params, address common.Address) bool {
	ret := _m.Called(params, address)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailableStaticPrecompile")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*vmtypes.Params, common.Address) bool); ok {
		r0 = rf(params, address)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// EVMKeeper_IsAvailableStaticPrecompile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailableStaticPrecompile'
type EVMKeeper_IsAvailableStaticPrecompile_Call struct {
	*mock.Call
}

// IsAvailableStaticPrecompile is a helper method to define mock.On call
//   - params *vmtypes.Params
//   - address common.Address
func (_e *EVMKeeper_Expecter) IsAvailableStaticPrecompile(params interface{}, address interface{}) *EVMKeeper_IsAvailableStaticPrecompile_Call {
	return &EVMKeeper_IsAvailableStaticPrecompile_Call{Call: _e.mock.On("IsAvailableStaticPrecompile", params, address)}
}

func (_c *EVMKeeper_IsAvailableStaticPrecompile_Call) Run(run func(params *vmtypes.Params, address common.Address)) *EVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*vmtypes.Params), args[1].(common.Address))
	})
	return _c
}

func (_c *EVMKeeper_IsAvailableStaticPrecompile_Call) Return(_a0 bool) *EVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_IsAvailableStaticPrecompile_Call) RunAndReturn(run func(*vmtypes.Params, common.Address) bool) *EVMKeeper_IsAvailableStaticPrecompile_Call {
	_c.Call.Return(run)
	return _c
}

// IsContract provides a mock function with given fields: ctx, address
func (_m *EVMKeeper) IsContract(ctx types.Context, address common.Address) bool {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for IsContract")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(types.Context, common.Address) bool); ok {
		r0 = rf(ctx, address)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// EVMKeeper_IsContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsContract'
type EVMKeeper_IsContract_Call struct {
	*mock.Call
}

// IsContract is a helper method to define mock.On call
//   - ctx types.Context
//   - address common.Address
func (_e *EVMKeeper_Expecter) IsContract(ctx interface{}, address interface{}) *EVMKeeper_IsContract_Call {
	return &EVMKeeper_IsContract_Call{Call: _e.mock.On("IsContract", ctx, address)}
}

func (_c *EVMKeeper_IsContract_Call) Run(run func(ctx types.Context, address common.Address)) *EVMKeeper_IsContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *EVMKeeper_IsContract_Call) Return(_a0 bool) *EVMKeeper_IsContract_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_IsContract_Call) RunAndReturn(run func(types.Context, common.Address) bool) *EVMKeeper_IsContract_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccount provides a mock function with given fields: ctx, address, account
func (_m *EVMKeeper) SetAccount(ctx types.Context, address common.Address, account statedb.Account) error {
	ret := _m.Called(ctx, address, account)

	if len(ret) == 0 {
		panic("no return value specified for SetAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Context, common.Address, statedb.Account) error); ok {
		r0 = rf(ctx, address, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EVMKeeper_SetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccount'
type EVMKeeper_SetAccount_Call struct {
	*mock.Call
}

// SetAccount is a helper method to define mock.On call
//   - ctx types.Context
//   - address common.Address
//   - account statedb.Account
func (_e *EVMKeeper_Expecter) SetAccount(ctx interface{}, address interface{}, account interface{}) *EVMKeeper_SetAccount_Call {
	return &EVMKeeper_SetAccount_Call{Call: _e.mock.On("SetAccount", ctx, address, account)}
}

func (_c *EVMKeeper_SetAccount_Call) Run(run func(ctx types.Context, address common.Address, account statedb.Account)) *EVMKeeper_SetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].(common.Address), args[2].(statedb.Account))
	})
	return _c
}

func (_c *EVMKeeper_SetAccount_Call) Return(_a0 error) *EVMKeeper_SetAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EVMKeeper_SetAccount_Call) RunAndReturn(run func(types.Context, common.Address, statedb.Account) error) *EVMKeeper_SetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// SetCode provides a mock function with given fields: ctx, hash, bytecode
func (_m *EVMKeeper) SetCode(ctx types.Context, hash []byte, bytecode []byte) {
	_m.Called(ctx, hash, bytecode)
}

// EVMKeeper_SetCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCode'
type EVMKeeper_SetCode_Call struct {
	*mock.Call
}

// SetCode is a helper method to define mock.On call
//   - ctx types.Context
//   - hash []byte
//   - bytecode []byte
func (_e *EVMKeeper_Expecter) SetCode(ctx interface{}, hash interface{}, bytecode interface{}) *EVMKeeper_SetCode_Call {
	return &EVMKeeper_SetCode_Call{Call: _e.mock.On("SetCode", ctx, hash, bytecode)}
}

func (_c *EVMKeeper_SetCode_Call) Run(run func(ctx types.Context, hash []byte, bytecode []byte)) *EVMKeeper_SetCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Context), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *EVMKeeper_SetCode_Call) Return() *EVMKeeper_SetCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *EVMKeeper_SetCode_Call) RunAndReturn(run func(types.Context, []byte, []byte)) *EVMKeeper_SetCode_Call {
	_c.Run(run)
	return _c
}

// NewEVMKeeper creates a new instance of EVMKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEVMKeeper(t interface {
	mock.TestingT
	Cleanup(func())
}) *EVMKeeper {
	mock := &EVMKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
